name: RentWarp
version: 1.4.1
description: Economy Warp Plugin
author: Fahlur
depend: [Vault]
main: me.fahlur.rentwarp.rentwarp
commands:
  colors:
    description: List valid colors for greetings
    aliases: c
    usage: /colors 
  mywarps:
      description: Lists your warps
      aliases: myw
      usage: /mywarps
  movewarp:
      description: Move your warp
      aliases: mw
      usage: /movewarp
  setwarp:
      description: Create your warp
      aliases: [createwarp,addwarp,rwsetwarp]
      usage: /setwarp
  delwarp:
      description: Delete your warp
      aliases: [rwdelwarp,remwarp,rwremwarp]
      usage: /delwarp
  warpgreet:
      description: Update your warps greeting
      aliases: wg
      usage: /warpgreet 
  warp:
      description: Main Command
      aliases: [rwwarp,w, warps]
      usage: /warp 
  warpcost:
      description: Displays current cost for a warp
      aliases: wc
      usage: /warpcost 
  warpinfo:
      description: Displays information about a warp
      aliases: wi
      usage: /warpinfo 
  addtime:
      description: Extends warp time duration
      aliases: at
      usage: /addtime 
  warpexempt:
      description: Exempts a warp from rent
      aliases: we
      usage: /warpexempt 
  rentwarp:
      description: Main plugin command
      aliases: rw
      usage: /rentwarp 
Permissions:
  RentWarp.*:
    description: Gives access to everything
    children:
        RentWarp.Player.Help: true
        RentWarp.Player.List: true
        RentWarp.Player.Warp: true
        RentWarp.Player.Info: true
        RentWarp.Player.Create: true
        RentWarp.Player.Delete: true
        RentWarp.Player.Addtime: true
        RentWarp.Player.Greeting: true
        RentWarp.Player.rentwarpcommand: true
        RentWarp.Warp.Exempt: true
        RentWarp.Admin.Reload: true
        RentWarp.Admin.Delete: true
        RentWarp.Admin.Greet: true
        RentWarp.Admin.RentExempt: true
        RentWarp.Admin.Addtime: true
        RentWarp.Admin.CoolDownExempt: true
        RentWarp.Admin.Move: true
  RentWarp.Player.*:
    description: Gives access to all player features
    children:
        RentWarp.Player.Help: true
        RentWarp.Player.List: true
        RentWarp.Player.Warp: true
        RentWarp.Player.Info: true
        RentWarp.Player.Create: true
        RentWarp.Player.Delete: true
        RentWarp.Player.Addtime: true
        RentWarp.Player.Greeting: true
        RentWarp.Player.rentwarpcommand: true
  RentWarp.Warp.Exempt:
    description: Allows players to be exempt from warp fees
    default: op
  RentWarp.Player.Help:
    description: Allows you to see the plugins help page
    default: op
  RentWarp.Player.List:
    description: Allows you to list warps
    default: op
  RentWarp.Player.Warp:
    description: Allows you to warp
    default: op
  RentWarp.Player.Info:
    description: Allows you to get information on a warp
    default: op
  RentWarp.Player.Create:
    description: Allows you to create a warp
    default: op
  RentWarp.Admin.Reload:
    description: Allows you to reload the plugin
    default: op
  RentWarp.Player.Delete:
    description: Allows you to delete a warp
    default: op
  RentWarp.Admin.Delete:
    description: Allows you to delete a warp
    default: op
  RentWarp.Admin.RentExempt:
    description: Allows you to exempt a warp from rent
    default: op  
  RentWarp.Admin.CoolDownExempt:
    description: Allows for instant warp
    default: op  
  RentWarp.Admin.Move:
    description: Allows you to move a warp
    default: op  
